# Generated by Django 4.2.5 on 2023-12-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_customer_address_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
