# Generated by Django 4.2.5 on 2024-02-06 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customer_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('officeid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('regdate', models.DateField()),
            ],
        ),
    ]
