# Generated by Django 4.2.5 on 2024-03-06 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
