# Generated by Django 4.2.5 on 2023-11-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_hospital_category_delete_hospital_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='approval_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1),
        ),
    ]
