# Generated by Django 4.2.5 on 2023-11-15 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_hospital_activation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='activation_status',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='approval_status',
        ),
    ]
